### ISSUE TITLE
Error installing new version

### ISSUE THREAD

**Issue by seifreed** [fxb-cocacoding/yara-signator#4]
This is what I got when I tried to update to the new version:

```
Results :

Failed tests:   testInsertIntoBlacklist(tests.postgres_test.BlacklistTest): expected:<0> but was:<4>

Tests in error: 
  tests.postgres_test.BlacklistTest: ERROR: current transaction is aborted, commands ignored until end of transaction block

Tests run: 3, Failures: 1, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.985 s
[INFO] Finished at: 2020-10-21T11:32:42+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project yara-signator: There are test failures.
[ERROR] 
[ERROR] Please refer to /{hidden}/yara-signator/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

Prior to this I successfully updated the other components.

**Comment by xor3r** [comment]
I've encountered the same problem while doing a clean installation of v0.5.0 on Ubuntu 18.04 with Postgres 11.
The test seems to be failing with: 
```ERROR: partition "blacklist_list_rest" would overlap partition "blacklist_list_0"```.
The last command which executes with failure is: 
```CREATE TABLE IF NOT EXISTS blacklist_list_rest PARTITION OF blacklist FOR VALUES FROM ('?') TO ('?ffffffffffffffffffffffffffffffffffffffffffffffffffffffff');```

UPD: I think that the tests which are triggered are [here](https://github.com/fxb-cocacoding/yara-signator/blob/0b414b216031287456344378fa3863fe6647a5ed/src/test/java/tests/postgres_test/BlacklistTest.java), but the problem may be with Postgres constraints themselves, as after I had commented out these assertions, the above error with **overlapping** was not solved.

**Comment by seifreed** [comment]
Any update here @fxb-cocacoding  ?

**Comment by fxb-cocacoding** [comment]
Hi, I am currently working on a new release where this will be fixed.

**Comment by seifreed** [comment]
Super! Thanks!!! Any ETA? We can help somehow?

**Comment by fxb-cocacoding** [comment]
I try to release it in the next week, maybe a bit earlier depending if I run into any more issues.
Thanks for your support, testing is already a great help!

**Comment by fxb-cocacoding** [comment]
Problem solved: For those who are interested: https://github.com/fxb-cocacoding/yara-signator/issues/5
The fix will be available in the new release!
